#ifndef MYSQL_AVID_ERRORNO_H
#define MYSQL_AVID_ERRORNO_H

#define CANNOT_CREATE_TABLE_FILE (-1)
#define CANNOT_CLOSE_TABLE_FILE (-2)
#define CANNOT_OPEN_TABLE_FILE (-3)
#define CANNOT_DELETE_TABLE_FILE (-4)

#endif  // MYSQL_AVID_ERRORNO_H
